language: c++
services:
    - docker



before_install:
    - docker pull davidpy1992/softrd-dev

script:
    - docker run davidpy1992/softrd-dev /bin/bash
    - cd /softrd
    - mkdir build-wasm
    - pwd
    - emcmake cmake ..
