language: c++
services:
    - docker



before_install:
    - docker run -it $(pwd):/softrd davidpy1992/softrd-dev /bin/bash
    - docker ps -a

before_script:

script:
    - docker exec davidpy1992/softrd-dev pwd
    - docker exec davidpy1992/softrd-dev "mkdir /softrd/core/build-wasm && cd /softrd/core/build-wasm && emcmake cmake ..