cc_library(
    name = "vertex_shader",
    hdrs = ["vertex_shader.h"],
    srcs = ["vertex_shader.cc"],
    deps = [
        "//src/math:vector",
        "//src/math:matrix",
        "//src/components:vertex",
    ]
)