package(default_visibility = ["//visibility:public"])

cc_library(
    name = "device",
    hdrs = ["device.h"],
    srcs = ["device.cc"],
    deps = [
        "//third_party/sdl2_lib:sdl2",
        "//src/math:vector",
        "//src/utils:util",
    ]
)