package(default_visibility = ["//visibility:public"])

cc_library(
    name = "vertex",
    hdrs = ["vertex.h"],
    deps = [
        "//src/math:vector",
    ]
)

cc_library(
    name = "fragment",
    hdrs = ["fragment.h"],
    deps = [
        "//src/math:vector",
    ]
)

cc_library(
    name = "primitive",
    hdrs = ["primitive.h"],
    deps = [
        "//src/modules:vertex_shader",
    ]
)

cc_library(
    name = "mesh",
    hdrs = ["mesh.h"],
    deps = [
    ]
)

cc_library(
    name = "camera",
    hdrs = ["camera.h"],
    deps = [
        "//src/math:math_lib",
    ]
)
