package(default_visibility = ["//visibility:public"])

cc_library(
    name = "renderer_api",
    hdrs = ["renderer_api.h"],
    srcs = ["renderer_api.cc"],
    deps = [
        "//src/renderer:rendering_pipeline",
    ]
)
