package(default_visibility = ["//visibility:public"])

cc_library(
    name = "device",
    hdrs = ["device.h"],
    srcs = ["device.cc"],
    deps = [
        "@sdl2//:SDL2",
        "@sdl2//:SDL2main",
        "@sdl2//:SDL2_ttf",
        "//src/math:vector",
        "//src/utils:util",
    ]
)