# workspace
new_local_repository(
    name = "soil",
    path = "/path/to/coworkers-project",
    build_file = "coworker.BUILD",
)

new_local_repository(
    name = "sdl2",
    path = "third_party/sdl2",
    build_file = "third_party/sdl2.BUILD",
)

new_local_repository(
    name = "assimp",
    path = "third_party/assimp",
    build_file = "third_party/assimp.BUILD",
)

new_local_repository(
    name = "soil",
    path = "third_party/soil",
    build_file = "third_party/soil.BUILD",
)



