cc_library(
    name = "rendering_pipeline",
    hdrs = ["rendering_pipeline.h"],
    srcs = ["rendering_pipeline.cc"],
    deps = [
        "//src/components:camera",
        "//src/modules:vertex_shader",
        "//src/modules:rasterizer",
        "//src/modules:fragment_shader",
        "//src/modules:per_sample_processing",
        "//src/components:model",
        "//src/utils:util",
        "//src/modules:vertex_loader",
    ]
)
